version: 2.1

jobs:
  deploy-laravel:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Run ssh on server
          command: apt-get update && apt-get install -y openssh-client
      - run:
          name: SSH to Server
          command: |
            echo "Access the server"
            ssh $USERNAME@$HOST -o StrictHostKeyChecking=no
            cd /home/ubuntu/devops ./deploy.sh


workflows:
  version: 2
  deploy:
    jobs:
      - deploy-laravel:
          filters:
            branches:
              only:
                - master
